### ISSUE TITLE
initializing vars

### ISSUE THREAD

**Issue by lovelyncutecode** [KoDDrovosek/IOSIF#19]
https://github.com/KoDDrovosek/IOSIF/blob/95be4e549a3417c212bcc69e96664bda71d2665c/topicStore/topicStore.go#L14

(это тоже придирка) когда ты создаешь пустую map/slice, лучше делать это с помощью make, а не литералом. так как бы читабельнее

**Comment by KoDDrovosek** [comment]
https://github.com/KoDDrovosek/IOSIF/pull/26
