### ISSUE TITLE
confusing naming

### ISSUE THREAD

**Issue by lovelyncutecode** [KoDDrovosek/IOSIF#20]
Supervisor, Cleaner etc conventionally suit interfaces, because they define behavior.
Factory,  Repository - structs, because they define entities.
Verbs like Clean, Send are good for methods, because they define actions.

Otherwise, it is hard to read the code. Besides that Distributor means that it 'fans out' data, but doesn't send it to the specific queue.

**Comment by KoDDrovosek** [comment]
Currently we are working on new version . We try to stick to the correct naming of variables. https://github.com/KoDDrovosek/IOSIF/pull/25
