### ISSUE TITLE
proper error handling

### ISSUE THREAD

**Issue by lovelyncutecode** [KoDDrovosek/IOSIF#9]
log.Fatal - 💩
https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully

**Comment by lovelyncutecode** [comment]
https://dave.cheney.net/2015/11/05/lets-talk-about-logging

**Comment by KoDDrovosek** [comment]
https://github.com/KoDDrovosek/IOSIF/pull/10

**Comment by KoDDrovosek** [comment]
https://github.com/KoDDrovosek/IOSIF/pull/10
